# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = ENV['api_key']
  config.secret_key = ENV['secret_key']
  config.default_from = 'naoxy.slmk@gmail.com'
 

end
